#!/usr/bin/bash

cmdname=`basename $0`
function usage()
{
  echo "Usage: ${cmdname} <SRRlist generated by download_accession.sh>" 1>&2
  echo "  Example: ${cmdname} metadata/PRJNA1445099.SRR.txt" 1>&2
}

# check options
dry=FALSE
while getopts d option
do
  case ${option} in
    d) dry=TRUE;;
    *)
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

# check arguments
if [ $# -ne 1 ]; then
  usage
  exit 1
fi

if [ "$dry" = TRUE ]; then
    ex(){ echo "$1"; }
else
    ex(){ echo "$1"; eval "$1"; }
fi

#if [ "$dry" = TRUE ]; then
#    ex(){ echo $1 }
#else
#    ex(){ echo $1; eval $1; }
#fi

samplelist=$1

while IFS=$'\t' read -r srr assay layout; do
    outdir="${assay}/fastq"
    ex "mkdir -p \"$outdir\""

    if [ "$layout" = "PAIRED" ]; then
        ex "pfastq-dump -t 12 --gzip --split-files -O \"$outdir\" -s \"$srr\""
    else
        ex "pfastq-dump -t 12 --gzip -O \"$outdir\" -s \"$srr\""
    fi
done < "$samplelist"
